import type { CheckStatus, ProductionReadinessReport } from "./types.ts";

const STATUS_COLOR: Record<CheckStatus, string> = {
  PASS: "#0f9d58",
  FAIL: "#d93025",
  BLOCKED: "#b31412",
  NOT_RUN: "#9aa0a6",
  SKIPPED: "#9aa0a6",
  REQUIRES_HUMAN_REVIEW: "#f29900",
};

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function renderHtmlReport(report: ProductionReadinessReport): string {
  const generated = new Date(report.generatedAt).toISOString();
  const scoreText = report.overallScore === null ? "N/A" : report.overallScore.toFixed(1);

  const rows = report.categories
    .map((c) => {
      const score = c.countedInScore ? c.score.toFixed(0) : "—";
      const evidence =
        c.evidence.length > 0
          ? `<ul class="evidence">${c.evidence.map((e) => `<li>${escapeHtml(e)}</li>`).join("")}</ul>`
          : "";
      return `<tr>
        <td>${escapeHtml(c.category)}</td>
        <td><span class="badge" style="background:${STATUS_COLOR[c.status]}">${c.status.replace(/_/g, " ")}</span></td>
        <td>${score}</td>
        <td>${c.weight}</td>
        <td>${escapeHtml(c.details)}${evidence}</td>
      </tr>`;
    })
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Production Readiness Report — ${escapeHtml(report.projectName)}</title>
<style>
  :root { color-scheme: light; }
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 2.5rem; color: #1f2124; background: #fff; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .meta { color: #5f6368; font-size: 0.85rem; margin-bottom: 1.5rem; }
  .summary { display: flex; gap: 2rem; align-items: baseline; margin-bottom: 0.5rem; }
  .score { font-size: 2.25rem; font-weight: 700; }
  .formula { font-size: 0.8rem; color: #5f6368; background: #f8f9fa; border-left: 3px solid #dadce0; padding: 0.5rem 0.75rem; margin: 1rem 0 2rem; }
  table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
  th, td { text-align: left; padding: 0.6rem 0.75rem; border-bottom: 1px solid #e8eaed; vertical-align: top; }
  th { color: #5f6368; font-weight: 600; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.03em; }
  .badge { color: #fff; padding: 0.15rem 0.5rem; border-radius: 999px; font-size: 0.75rem; font-weight: 600; white-space: nowrap; }
  .evidence { margin: 0.4rem 0 0; padding-left: 1.1rem; color: #5f6368; font-size: 0.8rem; }
  footer { margin-top: 2rem; font-size: 0.75rem; color: #9aa0a6; border-top: 1px solid #e8eaed; padding-top: 1rem; }
  @media print { body { margin: 1cm; } }
</style>
</head>
<body>
  <h1>Production Readiness Report</h1>
  <div class="meta">${escapeHtml(report.projectName)} — generated ${generated}</div>
  <div class="summary">
    <div>
      <div class="score" style="color:${STATUS_COLOR[report.overallStatus]}">${scoreText}<span style="font-size:1rem;color:#5f6368"> / 100</span></div>
    </div>
    <span class="badge" style="background:${STATUS_COLOR[report.overallStatus]}">${report.overallStatus.replace(/_/g, " ")}</span>
  </div>
  <div class="formula">${escapeHtml(report.scoreFormula)}</div>
  <table>
    <thead><tr><th>Category</th><th>Status</th><th>Score</th><th>Weight</th><th>Details</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <footer>Generated by AI QA Agent from real execution evidence. Categories that were never run are marked NOT RUN, never PASS.</footer>
</body>
</html>`;
}
