import type { ProductionReadinessReport } from "./types.ts";

const STATUS_LABEL: Record<string, string> = {
  PASS: "✅ PASS",
  FAIL: "❌ FAIL",
  BLOCKED: "⛔ BLOCKED",
  NOT_RUN: "⬜ NOT RUN",
  SKIPPED: "⏭️ SKIPPED",
  REQUIRES_HUMAN_REVIEW: "🔎 REQUIRES HUMAN REVIEW",
};

export function renderMarkdownReport(report: ProductionReadinessReport): string {
  const lines: string[] = [];
  lines.push(`# Production Readiness Report — ${report.projectName}`);
  lines.push("");
  lines.push(`Generated: ${new Date(report.generatedAt).toISOString()}`);
  lines.push("");
  lines.push(`**Overall status:** ${STATUS_LABEL[report.overallStatus] ?? report.overallStatus}`);
  lines.push(
    `**Overall score:** ${report.overallScore === null ? "N/A (nothing was run)" : `${report.overallScore.toFixed(1)} / 100`}`,
  );
  lines.push("");
  lines.push(`> ${report.scoreFormula}`);
  if (report.excludedFromScore.length > 0) {
    lines.push(`>
> Excluded from score: ${report.excludedFromScore.join(", ")}`);
  }
  lines.push("");
  lines.push("## Categories");
  lines.push("");
  lines.push("| Category | Status | Score | Weight | Details |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const c of report.categories) {
    const score = c.countedInScore ? c.score.toFixed(0) : "—";
    lines.push(
      `| ${c.category} | ${STATUS_LABEL[c.status] ?? c.status} | ${score} | ${c.weight} | ${c.details.replace(/\|/g, "\\|")} |`,
    );
  }
  lines.push("");
  for (const c of report.categories) {
    if (c.evidence.length === 0) continue;
    lines.push(`### ${c.category} evidence`);
    for (const e of c.evidence) lines.push(`- ${e}`);
    lines.push("");
  }
  lines.push("---");
  lines.push(
    "_Generated by AI QA Agent from real execution evidence. Every status above reflects an actual run, " +
      "not a simulation — categories that were never run are marked NOT RUN, never PASS._",
  );
  return lines.join("\n");
}
